room_names = [
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine",
    "The Creepy Mine"
    
    # "The Fort of the Fury", "The golden Turret of the Destruction", "The Lab of the Blessing", "The Apothecary of the Renewal", "The Elemental Treasury of Renewal", "The Fortress of the Reawakened", "The Green Garden of Chaos", "The Twisted Chamber of the Void", "The Disturbing Pantry", "The Alabaster Manse of War", "The Hidden Ruin of the Vanquished", "The Nest of Pain",
    # "The Scorched Nursery", "The Ancient Barracks", "The Farm of Betrayal", "The Pool of Undead", "The Bleeding Manse", "The Unholy Armoury",
    # "The Noxious Sepulchre of Chaos", "The Lunar Fortress of the Treasure", "The Alluring Foundry of the Primeval Enchantment",
    # "The Legendary Hospital of the Misty Death", "The Spectacular Church of Dreams", "The Chaotic Mine", "The Untamed Church of Flame",
    # "The Twisted Menagerie of the Flame", "The Aviary of the Power", "The Miscreant Stockade", "The Dungeon of Shadow", "The Infernal Gallery",
    # "The Fiery Castle of the Unholy Imprisoned", "The Merciless Pantry", "The Foundry of Schemes", "The Fabled Caves of the Plain Schemes",
    # "The Secluded Passage", "The Cathedral of the Tranquillity", "The Observatory of Eternity", "The Elder Pantry of Imprisoned", "The Miscreant Tower of the Despair",
    # "The Giant Warehouse of Legends", "The Wooden Nest of Banishment", "The Fort of the Wrath", "The Private Church of the Pleasure", "The Silver Pantry of the Spirits",
    # "The Phased Rift of the Warped Death", "The Lab of the Terror", "The Pagoda of Horde", "The Tavern of Terror", "The Severe Maze of the Horde",
    # "The Steel Stronghold", "The Glorious Tunnel of the Gloom", "The Pantry of the War", "The Immense Nursery of the Sloth", "The Fane of Abyss",
    # "The Cluttered Sanctum of the Renewal", "The Cluttered Stockade", "The Greenhouse of Frost", "The Holy Spire of the Noxious Eternity",
    # "The Bleeding Catacomb of the Torture", "The Black Hall of the Ascension", "The Sliding Plaza of the Time", "The Fountain of Illusion", "The Floating Caves",
    # "The Corridor of Time", "The Spire of Sloth", "The Dusty Lair of the Woe", "The Fallen Nursery of Terror", "The Monolith of the Secrets", "The Quarters of the Vanquished",
    # "The Lost Stronghold", "The Obsidian Tavern of the Dirty Abyss", "The Portal of Spirits", "The Home of the Legends", "The Blue Keep of the Heavens", "The Plaza of the Worms",
    # "The Rampart of Blood", "The Creepy Bedroom", "The Vault of Damnation", "The Cathedral of the Oblivion", "The Looping Pillar", "The Simple Dome of Sorcery",
    # "The Insane Temple of Desire", "The Red Cellar of Curses", "The Graveyard of Wyrms", "The Unstable Dome of the Warped Mystery", "The Boring Fortress of the Phased Madness",
    # "The Shrine of the Order", "The Rift of Light", "The Infinite Fortress", "The Lunar Bedroom", "The Buried Cathedral of the Screams", "The Spooky Portal of the Gods",
    # "The Quarters of Light", "The Eldritch Treasury of the Cursed Sorcery", "The Infested Hideout of the White Void", "The Endless Lair of the Contaminated Mystery",
    # "The Primeval Stairs of the Insanity", "The Legendary Bridge of the Amazing Dreams", "The Small Rift of Flame", "The Polluted Kennel of Mystery", "The Hellish Lab of the Ghosts"
]


room_descriptions = [
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon.",
    "A short worn statue in a gloomy swamp marks the entrance to this dungeon."
]
