# Generated by Django 3.0.3 on 2020-02-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200204_1527'),
        ('adventure', '0002_auto_20200204_1759'),
    ]

    operations = [
    ]
