# Generated by Django 3.0.3 on 2020-02-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_merge_20200205_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='x_cordinate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y_cordinate',
            field=models.IntegerField(default=0),
        ),
    ]
