# Generated by Django 3.0.3 on 2020-02-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200205_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='temp',
        ),
    ]
