# Generated by Django 3.0.3 on 2020-02-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200205_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
