# Generated by Django 3.0.3 on 2020-02-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_room_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='temp',
        ),
        migrations.AddField(
            model_name='player',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
