# Generated by Django 3.0.3 on 2020-02-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_remove_room_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='x_cordinate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='y_cordinate',
            field=models.IntegerField(default=0),
        ),
    ]
